Assignment

In this assignment, you'll be working with the U.S. Education Dataset from Kaggle. The data gives detailed state level information on several facets of the state of education on an annual basis. To learn more about the data and the column descriptions, click the Kaggle link above.

Access this data from the Thinkful database using the following credentials:

postgres_user = 'dsbc_student'
postgres_pw = '7*.8G9QH21'
postgres_host = '142.93.121.174'
postgres_port = '5432'
postgres_db = 'useducation'

To complete this assignment, submit a link to a Jupyter notebook containing your solutions to the following tasks:

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import warnings

warnings.filterwarnings('ignore')

In [2]:
postgres_user = 'dsbc_student'
postgres_pw = '7*.8G9QH21'
postgres_host = '142.93.121.174'
postgres_port = '5432'
postgres_db = 'useducation'

engine = create_engine('postgresql://{}:{}@{}:{}/{}'.format(
    postgres_user, postgres_pw, postgres_host, postgres_port, postgres_db))

data = pd.read_sql_query('select * from useducation',con=engine)

# no need for an open connection, 
# as we're only doing a single query
engine.dispose()

    1. Determine all the variable types and find the fraction of the missing values for each variable.

In [9]:
data.head(100)

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,471564.0,196386.0,676174.0,208.327876,252.187522,207.963517,NaN
1,1992_ALASKA,ALASKA,1992,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,79117.0,30847.0,112335.0,NaN,NaN,NaN,258.859712
2,1992_ARIZONA,ARIZONA,1992,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,437127.0,175210.0,614881.0,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,1992,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,281338.0,123113.0,405259.0,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,1992,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,3286034.0,1372011.0,4717112.0,208.398961,260.892247,196.764414,NaN
5,1992_COLORADO,COLORADO,1992,NaN,3185173.0,163253.0,1307986.0,1713934.0,3264826.0,1642466.0,...,50648.0,45025.0,34533.0,394904.0,160299.0,562613.0,221.023429,272.398433,213.480890,266.419687
6,1992_CONNECTICUT,CONNECTICUT,1992,NaN,3834302.0,143542.0,1342539.0,2348221.0,3721338.0,2148041.0,...,38058.0,33691.0,28366.0,304284.0,126917.0,436932.0,226.798480,273.739345,222.417599,264.713904
7,1992_DELAWARE,DELAWARE,1992,NaN,645233.0,45945.0,420942.0,178346.0,638784.0,372722.0,...,8272.0,8012.0,6129.0,67495.0,28338.0,96296.0,217.899972,262.868585,206.389052,261.577921
8,1992_DISTRICT_OF_COLUMBIA,DISTRICT_OF_COLUMBIA,1992,NaN,709480.0,64749.0,0.0,644731.0,742893.0,329160.0,...,5832.0,5000.0,3433.0,47009.0,18173.0,70000.0,192.600553,234.924621,178.557612,265.976765
9,1992_FLORIDA,FLORIDA,1992,NaN,11506299.0,788420.0,5683949.0,5033930.0,11305642.0,5166374.0,...,164416.0,142372.0,100835.0,1276685.0,511557.0,1819706.0,213.689751,259.908848,204.882606,262.118986
10,1992_GEORGIA,GEORGIA,1992,NaN,5536901.0,398701.0,2798674.0,2339526.0,5535942.0,3043984.0,...,99648.0,92374.0,63646.0,787599.0,315539.0,1106441.0,215.594906,259.359434,206.844175,NaN
11,1992_HAWAII,HAWAII,1992,NaN,996809.0,71273.0,903443.0,22093.0,1040121.0,536115.0,...,13754.0,11750.0,9051.0,107242.0,43882.0,151649.0,214.056666,257.410887,200.880272,NaN
12,1992_IDAHO,IDAHO,1992,NaN,859329.0,69138.0,531912.0,258279.0,886161.0,473505.0,...,18607.0,18880.0,14593.0,146573.0,66541.0,214345.0,221.562534,275.090294,NaN,NaN
13,1992_ILLINOIS,ILLINOIS,1992,NaN,9748650.0,597077.0,3073178.0,6078395.0,9850560.0,5010400.0,...,133120.0,134317.0,106475.0,1111167.0,495562.0,1646411.0,NaN,NaN,NaN,NaN
14,1992_INDIANA,INDIANA,1992,NaN,5060274.0,257044.0,2578149.0,2225081.0,5182754.0,2598925.0,...,73760.0,75477.0,62234.0,601890.0,278161.0,883276.0,221.037742,270.098944,219.763258,NaN
15,1992_IOWA,IOWA,1992,NaN,2663934.0,125665.0,1176205.0,1362064.0,2795774.0,1446478.0,...,37692.0,36892.0,33057.0,299253.0,138907.0,442752.0,229.884078,283.360009,222.852939,NaN
16,1992_KANSAS,KANSAS,1992,NaN,2245348.0,121625.0,903199.0,1220524.0,2234915.0,1165749.0,...,36013.0,33288.0,26706.0,284143.0,120960.0,407494.0,NaN,NaN,NaN,NaN
17,1992_KENTUCKY,KENTUCKY,1992,NaN,2642902.0,289902.0,1643109.0,709891.0,2518082.0,1343438.0,...,49666.0,49993.0,38029.0,400849.0,181786.0,597199.0,215.048158,262.241282,211.562307,NaN
18,1992_LOUISIANA,LOUISIANA,1992,NaN,3341253.0,367822.0,1848734.0,1124697.0,3362853.0,1888349.0,...,61125.0,55942.0,38368.0,490112.0,196891.0,698442.0,204.140211,249.983926,196.762268,NaN
19,1992_MAINE,MAINE,1992,NaN,1206819.0,73160.0,511654.0,622005.0,1228869.0,685350.0,...,17154.0,15969.0,13882.0,135320.0,59289.0,195882.0,231.638840,278.635384,228.380027,NaN
20,1992_MARYLAND,MARYLAND,1992,NaN,4658498.0,228336.0,1778834.0,2651328.0,4698374.0,2628891.0,...,60287.0,52815.0,40426.0,472622.0,189795.0,678498.0,217.317708,264.825493,209.645497,NaN
21,1992_MASSACHUSETTS,MASSACHUSETTS,1992,NaN,5517659.0,273946.0,1439051.0,3804662.0,5245560.0,2751871.0,...,66822.0,60702.0,52425.0,536029.0,230299.0,777050.0,226.597918,272.783201,223.160076,NaN
22,1992_MICHIGAN,MICHIGAN,1992,NaN,9963137.0,537917.0,2539380.0,6885840.0,10170688.0,4681327.0,...,118963.0,114282.0,90655.0,968910.0,419351.0,1398802.0,219.878352,267.353194,NaN,NaN
23,1992_MINNESOTA,MINNESOTA,1992,NaN,4684684.0,194092.0,2380754.0,2109838.0,4981125.0,2534882.0,...,62606.0,59810.0,53813.0,500938.0,224426.0,731758.0,228.493596,282.392205,218.301709,NaN
24,1992_MISSISSIPPI,MISSISSIPPI,1992,NaN,1684706.0,277706.0,901199.0,505801.0,1691990.0,956104.0,...,39839.0,38132.0,26328.0,321614.0,129554.0,451986.0,201.828261,246.458035,201.529328,NaN
25,1992_MISSOURI,MISSOURI,1992,NaN,4043682.0,255194.0,1903124.0,1885364.0,4197600.0,2168135.0,...,67098.0,64546.0,50534.0,531337.0,235437.0,785722.0,222.215600,271.131545,216.898079,NaN
26,1992_MONTANA,MONTANA,1992,NaN,828983.0,69947.0,337455.0,421581.0,781009.0,412219.0,...,12839.0,12124.0,10019.0,102124.0,44449.0,147127.0,NaN,NaN,222.301419,NaN
27,1992_NEBRASKA,NEBRASKA,1992,NaN,1542413.0,85423.0,492256.0,964734.0,1534046.0,909159.0,...,22133.0,21379.0,18999.0,177432.0,79975.0,260541.0,225.332648,277.654523,220.034963,NaN
28,1992_NEVADA,NEVADA,1992,NaN,1097076.0,45018.0,724032.0,328026.0,1251651.0,572623.0,...,18487.0,16250.0,12242.0,145687.0,57605.0,204330.0,NaN,NaN,NaN,NaN
29,1992_NEW_HAMPSHIRE,NEW_HAMPSHIRE,1992,NaN,1063391.0,31020.0,86296.0,946075.0,1066647.0,581123.0,...,15611.0,13537.0,10752.0,123475.0,47999.0,172479.0,229.664564,278.216326,223.466140,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,1993_LOUISIANA,LOUISIANA,1993,795719.0,3438321.0,397206.0,1876967.0,1164148.0,3427102.0,1898515.0,...,60077.0,56522.0,39826.0,485035.0,202283.0,700175.0,NaN,NaN,NaN,NaN
71,1993_MAINE,MAINE,1993,211511.0,1368095.0,77440.0,652164.0,638491.0,1321846.0,809278.0,...,17237.0,15844.0,13446.0,135445.0,59632.0,196113.0,NaN,NaN,NaN,NaN
72,1993_MARYLAND,MARYLAND,1993,751850.0,4918010.0,252211.0,1940713.0,2725086.0,4898895.0,2785206.0,...,61199.0,55285.0,40661.0,484461.0,197072.0,699517.0,NaN,NaN,NaN,NaN
73,1993_MASSACHUSETTS,MASSACHUSETTS,1993,862495.0,6121612.0,305113.0,1924321.0,3892178.0,5679261.0,3237228.0,...,69111.0,62412.0,51309.0,548850.0,232208.0,794236.0,NaN,NaN,NaN,NaN
74,2016_OKLAHOMA,OKLAHOMA,2016,672777.0,6103728.0,689756.0,2909651.0,2504321.0,6184152.0,3047217.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,1993_MICHIGAN,MICHIGAN,1993,1600650.0,11034174.0,594226.0,3326748.0,7113200.0,11430958.0,5411969.0,...,120049.0,116702.0,87447.0,973756.0,423081.0,1408541.0,NaN,NaN,NaN,NaN
76,1993_MINNESOTA,MINNESOTA,1993,781566.0,4862635.0,213724.0,2284106.0,2364805.0,5290504.0,2756415.0,...,63194.0,63105.0,54642.0,507979.0,233253.0,747888.0,NaN,NaN,NaN,NaN
77,1993_MISSISSIPPI,MISSISSIPPI,1993,329408.0,1170109.0,174870.0,612301.0,382938.0,1167032.0,652571.0,...,39236.0,39815.0,26156.0,319394.0,131112.0,452703.0,NaN,NaN,NaN,NaN
78,1993_MISSOURI,MISSOURI,1993,834636.0,4196601.0,271548.0,1939230.0,1985823.0,4234845.0,2229886.0,...,66445.0,66371.0,50195.0,536039.0,241874.0,791863.0,NaN,NaN,NaN,NaN
79,1993_MONTANA,MONTANA,1993,158875.0,813998.0,74386.0,445532.0,294080.0,833435.0,446245.0,...,12967.0,12834.0,10325.0,103488.0,46111.0,150082.0,NaN,NaN,NaN,NaN
80,1993_NEBRASKA,NEBRASKA,1993,281354.0,1625242.0,94308.0,509432.0,1021502.0,1642376.0,972575.0,...,22391.0,22611.0,18578.0,178475.0,81671.0,263723.0,NaN,NaN,NaN,NaN
81,1993_NEVADA,NEVADA,1993,222846.0,1148268.0,52876.0,753277.0,342115.0,1265367.0,611914.0,...,19305.0,17825.0,12749.0,153912.0,60727.0,215876.0,NaN,NaN,NaN,NaN
82,1993_NEW_HAMPSHIRE,NEW_HAMPSHIRE,1993,177722.0,1109743.0,34680.0,84342.0,990721.0,1091814.0,611158.0,...,15630.0,14118.0,10635.0,126173.0,49098.0,176563.0,NaN,NaN,NaN,NaN
83,1993_NEW_JERSEY,NEW_JERSEY,1993,653488.0,6747567.0,331924.0,3104597.0,3311046.0,6641624.0,3676378.0,...,84767.0,79459.0,64402.0,685132.0,288263.0,982620.0,NaN,NaN,NaN,NaN
84,1993_NEW_MEXICO,NEW_MEXICO,1993,281407.0,1217194.0,154018.0,897725.0,165451.0,1223185.0,587753.0,...,24182.0,24899.0,16767.0,200631.0,87768.0,290332.0,NaN,NaN,NaN,NaN
85,1993_NEW_YORK,NEW_YORK,1993,2663637.0,22688753.0,1276362.0,8848470.0,12563921.0,23934282.0,14029639.0,...,198259.0,188274.0,143055.0,1608489.0,743933.0,2384109.0,NaN,NaN,NaN,NaN
86,1993_NORTH_CAROLINA,NORTH_CAROLINA,1993,1112636.0,5583166.0,433602.0,3388466.0,1761098.0,5475174.0,3037814.0,...,85989.0,86093.0,60856.0,705410.0,305060.0,1018939.0,NaN,NaN,NaN,NaN
87,1993_NORTH_DAKOTA,NORTH_DAKOTA,1993,118793.0,580148.0,56254.0,243783.0,280111.0,588983.0,310940.0,...,9266.0,9329.0,8066.0,74760.0,35000.0,110375.0,NaN,NaN,NaN,NaN
88,1993_OHIO,OHIO,1993,1834239.0,10841606.0,509488.0,4156070.0,6176048.0,10385253.0,5522474.0,...,136317.0,141534.0,111932.0,1127686.0,517122.0,1662018.0,NaN,NaN,NaN,NaN
89,1993_OKLAHOMA,OKLAHOMA,1993,312817.0,1436505.0,99809.0,802783.0,533913.0,1428916.0,726475.0,...,48242.0,46153.0,34744.0,389548.0,162511.0,557515.0,NaN,NaN,NaN,NaN
90,1993_OREGON,OREGON,1993,509814.0,3141217.0,196584.0,1180698.0,1763935.0,3149126.0,1712282.0,...,41290.0,39500.0,32828.0,327629.0,147819.0,476285.0,NaN,NaN,NaN,NaN
91,1993_PENNSYLVANIA,PENNSYLVANIA,1993,1719829.0,12269422.0,695807.0,4781408.0,6792207.0,12809067.0,6856146.0,...,131575.0,130209.0,107244.0,1079271.0,496382.0,1579834.0,NaN,NaN,NaN,NaN
92,1993_RHODE_ISLAND,RHODE_ISLAND,1993,138939.0,919594.0,46215.0,351512.0,521867.0,901540.0,588044.0,...,11603.0,10650.0,8094.0,92255.0,38470.0,131190.0,NaN,NaN,NaN,NaN
93,1993_SOUTH_CAROLINA,SOUTH_CAROLINA,1993,631613.0,3031112.0,277419.0,1419961.0,1333732.0,2994038.0,1592384.0,...,50357.0,50591.0,33949.0,414217.0,176745.0,598206.0,NaN,NaN,NaN,NaN
94,1993_SOUTH_DAKOTA,SOUTH_DAKOTA,1993,107050.0,465650.0,52787.0,120851.0,292012.0,481665.0,265549.0,...,11086.0,11427.0,8936.0,89480.0,39971.0,130063.0,NaN,NaN,NaN,NaN
95,1993_TENNESSEE,TENNESSEE,1993,844668.0,3268642.0,334410.0,1535027.0,1399205.0,3286481.0,1969619.0,...,65646.0,64124.0,47668.0,534579.0,236542.0,780663.0,NaN,NaN,NaN,NaN
96,1993_TEXAS,TEXAS,1993,3535333.0,20267205.0,1233446.0,9919561.0,9114198.0,18574871.0,8914245.0,...,284394.0,274208.0,178889.0,2291961.0,927209.0,3339616.0,NaN,NaN,NaN,NaN
97,1993_UTAH,UTAH,1993,462323.0,1638305.0,116791.0,928596.0,592918.0,1665011.0,881924.0,...,35467.0,38031.0,31692.0,287657.0,137235.0,427582.0,NaN,NaN,NaN,NaN
98,1993_VERMONT,VERMONT,1993,97454.0,837540.0,34179.0,216778.0,586583.0,809853.0,405876.0,...,8457.0,7496.0,6227.0,65038.0,27377.0,94439.0,NaN,NaN,NaN,NaN
99,1993_VIRGINIA,VIRGINIA,1993,1032842.0,5918536.0,365601.0,2358711.0,3194224.0,5955333.0,3121277.0,...,81615.0,78443.0,60314.0,652886.0,278009.0,934081.0,NaN,NaN,NaN,NaN

In [5]:
# Data types
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1492 entries, 0 to 1491
Data columns (total 25 columns):
PRIMARY_KEY                     1492 non-null object
STATE                           1492 non-null object
YEAR                            1492 non-null int64
ENROLL                          1229 non-null float64
TOTAL_REVENUE                   1280 non-null float64
FEDERAL_REVENUE                 1280 non-null float64
STATE_REVENUE                   1280 non-null float64
LOCAL_REVENUE                   1280 non-null float64
TOTAL_EXPENDITURE               1280 non-null float64
INSTRUCTION_EXPENDITURE         1280 non-null float64
SUPPORT_SERVICES_EXPENDITURE    1280 non-null float64
OTHER_EXPENDITURE               1229 non-null float64
CAPITAL_OUTLAY_EXPENDITURE      1280 non-null float64
GRADES_PK_G                     1319 non-null float64
GRADES_KG_G                     1360 non-null float64
GRADES_4_G                      1361 non-null float64
GRADES_8_G                      1361 non-null float64
GRADES_12_G                     1361 non-null float64
GRADES_1_8_G                    1361 non-null float64
GRADES_9_12_G                   1361 non-null float64
GRADES_ALL_G                    1319 non-null float64
AVG_MATH_4_SCORE                536 non-null float64
AVG_MATH_8_SCORE                532 non-null float64
AVG_READING_4_SCORE             533 non-null float64
AVG_READING_8_SCORE             498 non-null float64
dtypes: float64(22), int64(1), object(2)
memory usage: 291.5+ KB

In [7]:
# Fraction of missing data
data.isnull().sum()/len(data)

PRIMARY_KEY                     0.000000
STATE                           0.000000
YEAR                            0.000000
ENROLL                          0.176273
TOTAL_REVENUE                   0.142091
FEDERAL_REVENUE                 0.142091
STATE_REVENUE                   0.142091
LOCAL_REVENUE                   0.142091
TOTAL_EXPENDITURE               0.142091
INSTRUCTION_EXPENDITURE         0.142091
SUPPORT_SERVICES_EXPENDITURE    0.142091
OTHER_EXPENDITURE               0.176273
CAPITAL_OUTLAY_EXPENDITURE      0.142091
GRADES_PK_G                     0.115952
GRADES_KG_G                     0.088472
GRADES_4_G                      0.087802
GRADES_8_G                      0.087802
GRADES_12_G                     0.087802
GRADES_1_8_G                    0.087802
GRADES_9_12_G                   0.087802
GRADES_ALL_G                    0.115952
AVG_MATH_4_SCORE                0.640751
AVG_MATH_8_SCORE                0.643432
AVG_READING_4_SCORE             0.642761
AVG_READING_8_SCORE             0.666220
dtype: float64

    2. Notice that the data has a time dimension (year). For this assignment, forget about time and treat all the observations as if they're from the same year. Choose a strategy to deal with the missing values for each variables. For which variables would filling in the missing values with some value make sense? For which might tossing out the records entirely make sense?

In [11]:
yearless = data.drop(columns=['YEAR'])
yearless[]

,PRIMARY_KEY,STATE,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,SUPPORT_SERVICES_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,735036.0,...,57948.0,58025.0,41167.0,471564.0,196386.0,676174.0,208.327876,252.187522,207.963517,NaN
1,1992_ALASKA,ALASKA,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,350902.0,...,9748.0,8789.0,6714.0,79117.0,30847.0,112335.0,NaN,NaN,NaN,258.859712
2,1992_ARIZONA,ARIZONA,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,1007732.0,...,55433.0,49081.0,37410.0,437127.0,175210.0,614881.0,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,483488.0,...,34632.0,36011.0,27651.0,281338.0,123113.0,405259.0,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,8520926.0,...,418418.0,363296.0,270675.0,3286034.0,1372011.0,4717112.0,208.398961,260.892247,196.764414,NaN

Given we understand some of the logic, revenue and expenditures are proportionate to the number of enrolled students. We can fill in the values for the *ENROLL* variable using a ratio between it and the number of graders e.g *GRADES_4_G* and others, but it is estimated to have a low accuracy.

Likewise, financial numbers like *TOTAL_EXPENDITURE* and others are almost directly proportionate to the number of students, and can be estimated using a ratio for the same state from other rows. However, average scores for graders should not be filled using any method and are better tossed out when null, simply because -in the case the score is a subject of our analysis- it would not be fair to assign a score that is affected by features we cannot measure in this dataset.

    3. Now, take into account the time factor. Replicate your second answer but this time fill in the missing values by using a statistic that is calculated within the year of the observation. For example, if you want to fill a missing value for a variable with the mean of that variable, calculate the mean by using only the observations for that specific year.

For a given state and a given year that contains null values, it would be more accurate and logical to fill values from 1 year before or after it, since the numbers are less likely to have a dramatic change for a year forward or backward. The year variable makes it easier to fill values from a closed timeframe that represents the same conditions and therefore our estimations would turn out more accurate.

    4. This time, fill in the missing values using interpolation (extrapolation).

We can interpolate the values from the closest years for the same state in order to have the closest estimation, using linear interpolation. If we had inflation ratios, or ratios that would describe changing financial obligations for the education sector, it would be even more accurate.

    5. Compare your results for the 2nd, 3rd, and 4th questions. Do you find any meaningful differences?

I assume that in our case, interpolation makes the most sense because since time and location are involved, we are looking to fill values from rows with similar conditions. This means that for the same state, the next or previous years are very close to the current year (the one with missing values) and would be the most accurate.